# Generated by Django 5.2.15 on 2026-07-08 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_role_roleuser_usermeta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'types',
            },
        ),
        migrations.CreateModel(
            name='ArtisteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(db_column='artist_id', on_delete=django.db.models.deletion.CASCADE, to='catalogue.artist')),
                ('type', models.ForeignKey(db_column='type_id', on_delete=django.db.models.deletion.CASCADE, to='catalogue.type')),
            ],
            options={
                'db_table': 'artiste_type',
            },
        ),
    ]
