# Generated by Django 5.2.15 on 2026-07-08 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_locality_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('poster_url', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_in', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bookable', models.BooleanField(default=False)),
                ('location', models.ForeignKey(blank=True, db_column='location_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.location')),
            ],
            options={
                'db_table': 'shows',
            },
        ),
        migrations.CreateModel(
            name='ArtisteTypeShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artiste_type', models.ForeignKey(db_column='artiste_type_id', on_delete=django.db.models.deletion.CASCADE, to='catalogue.artistetype')),
                ('show', models.ForeignKey(db_column='show_id', on_delete=django.db.models.deletion.CASCADE, to='catalogue.show')),
            ],
            options={
                'db_table': 'artiste_type_show',
            },
        ),
    ]
