# Generated by Django 5.2.15 on 2026-07-14 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermeta',
            name='affiliate_level',
            field=models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('premium', 'Premium')], default='free', max_length=10),
        ),
    ]
